In [2]:
import numpy as np

In [34]:
#generate random data points
n = [5,5,5]
c = 3
n_features = 2
d_features = 1
x1 = np.random.multivariate_normal([2,3],[[2,0.8],[0.8,3]],n[0])
x2 = np.random.multivariate_normal([5,4],[[1.5,0.6],[0.6,2]],n[1])
x3 = np.random.multivariate_normal([1,3],[[3.7,0.3],[0.3,2.5]],n[2])
X = np.vstack((x1,x2,x3))
print('Original data(2D):')
print(X)

Original data(2D):
[[ 3.0022021   6.07415614]
 [ 2.49223788  4.59196114]
 [ 4.00207226  3.48265408]
 [ 0.92775729  3.72491773]
 [ 2.67638636  5.06978723]
 [ 4.50309037  5.53769192]
 [ 2.63998213  0.7169063 ]
 [ 7.13948454  4.17420251]
 [ 6.41748961  5.52953526]
 [ 3.95246342  3.14740067]
 [ 0.97835729  1.73466187]
 [-0.8464021   4.38810842]
 [-0.22064443  4.3113048 ]
 [ 0.31317845  1.69652722]
 [ 4.74123861  2.10671862]]


In [35]:
#compute mean of c classes
mu1 = np.mean(x1,axis=0).reshape(1,n_features)
mu2 = np.mean(x2,axis=0).reshape(1,n_features)
mu3 = np.mean(x3,axis=0).reshape(1,n_features)
mu = np.mean(X,axis=0).reshape(1,n_features)
means = {'m1':mu1,'m2':mu2,'m3':mu3}
print('means:',means)

means: {'m1': array([[2.62013118, 4.58869526]]), 'm2': array([[4.93050202, 3.82114733]]), 'm3': array([[0.99314556, 2.84746419]])}


In [23]:
#compute covariance matrix of c classes
s1 = np.dot((x1-mu1).T,(x1-mu1))/5
s2 = np.dot((x2-mu2).T,(x2-mu2))/5
s3 = np.dot((x3-mu3).T,(x3-mu3))/5

In [37]:
print('covariance matrices:')
print(s1)
print(s2)
print(s3)

covariance matrices:
[[0.36525621 0.47633326]
 [0.47633326 2.34619444]]
[[0.29084277 0.07168205]
 [0.07168205 1.4514214 ]]
[[2.62257854 0.95436989]
 [0.95436989 2.65566347]]


In [38]:
#compute within class scatter matrix
sw = s1 + s2 + s3
print('within class scatter matrix:')
print(sw)

within class scatter matrix:
[[3.27867752 1.5023852 ]
 [1.5023852  6.45327931]]


In [39]:
#compute between class scatter matrix
sb = np.zeros((n_features,n_features))
for i in range(c):
    sb += n[i]*np.dot((means['m'+str(i+1)]-mu).T,(means['m'+str(i+1)]-mu))
print('between class scatter matrix:')
print(sb)

between class scatter matrix:
[[39.14611906  8.15562531]
 [ 8.15562531  7.61512393]]


In [27]:
#calculate sw^-1*sb
sw_inv = np.linalg.inv(sw)
print(sw_inv)
sw_inv_sb = np.dot(sw_inv,sb)
print(sw_inv_sb)

[[ 0.34142419 -0.07948682]
 [-0.07948682  0.17346527]]
[[14.10890874  2.70874308]
 [-1.84120634  0.28894176]]


In [28]:
#calculate eigen values and eigen vectors
lambd,vecs = np.linalg.eig(sw_inv_sb)

In [41]:
print('eigen values:',lambd)
print('eigen vectors:\n',vecs)

eigen values: [13.73807786  0.65977263]
eigen vectors:
 [[ 0.99075869 -0.19744171]
 [-0.13563631  0.98031463]]


In [43]:
#find projections
max_idx = np.argmax(lambd)
print(lambd[max_idx])
w = vecs[:,max_idx].reshape(n_features,d_features)
print('projection vector:\n',w)

13.73807786239171
projection vector:
 [[ 0.99075869]
 [-0.13563631]]


In [44]:
#reduce dimensionality
x1n = np.dot(x1,w)
x2n = np.dot(x2,w)
x3n = np.dot(x3,w)

In [45]:
Xn = np.vstack((x1n,x2n,x3n))
print('reduced data(1D):')
print(Xn)

reduced data(1D):
[[ 2.15058171]
 [ 1.84636969]
 [ 3.49271354]
 [ 0.41394951]
 [ 1.96400583]
 [ 3.71036384]
 [ 2.51834673]
 [ 6.50733297]
 [ 5.60817788]
 [ 3.48903569]
 [ 0.73403286]
 [-1.43376708]
 [-0.80337486]
 [ 0.08017358]
 [ 4.41167584]]
