In [1]:
import numpy as np

In [38]:
#generate random data points
n = [5,5,5]
c = 3
n_features = 2
x1 = np.random.multivariate_normal([2,3],[[2,0.8],[0.8,3]],n[0])
x2 = np.random.multivariate_normal([5,4],[[1.5,0.6],[0.6,2]],n[1])
x3 = np.random.multivariate_normal([1,3],[[3.7,0.3],[0.3,2.5]],n[2])
X = np.vstack((x1,x2,x3))

In [39]:
#compute mean of c classes
mu1 = np.mean(x1,axis=0).reshape(1,n_features)
mu2 = np.mean(x2,axis=0).reshape(1,n_features)
mu3 = np.mean(x3,axis=0).reshape(1,n_features)
mu = np.mean(X,axis=0).reshape(1,n_features)
means = {'m1':mu1,'m2':mu2,'m3':mu3}

In [40]:
#compute covariance matrix of c classes
s1 = np.dot((x1-mu1).T,(x1-mu1))/5
s2 = np.dot((x2-mu2).T,(x2-mu2))/5
s3 = np.dot((x3-mu3).T,(x3-mu3))/5

In [41]:
print(cov1)
print(cov2)
print(cov3)

[[19.44366124 24.1741697 ]
 [24.1741697  48.37490715]]
[[129.00374403  97.56676199]
 [ 97.56676199  81.08460223]]
[[11.52600567  9.3403758 ]
 [ 9.3403758  23.23462617]]


In [42]:
#compute within class scatter matrix
sw = s1 + s2 + s3
print(sw)

[[47.5293901   4.22808629]
 [ 4.22808629 35.04502613]]


In [43]:
#compute between class scatter matrix
sb = np.zeros((n_features,n_features))
for i in range(c):
    sb += n[i]*np.dot((means['m'+str(i+1)]-mu).T,(means['m'+str(i+1)]-mu))
print(sb)

[[44.42931964 11.17103731]
 [11.17103731  4.10682433]]


In [44]:
#calculate sw^-1*sb
sw_inv = np.linalg.inv(sw)
sw_inv_sb = np.dot(sw_inv,sb)
print(sw_inv_sb)

[[0.91625312 0.22704643]
 [0.20821899 0.08979455]]


In [45]:
#calculate eigen values and eigen vectors
lambd,vecs = np.linalg.eig(sw_inv_sb)

In [46]:
print(lambd)
print(vecs)

[0.96996475 0.03608292]
[[ 0.97314035 -0.24978079]
 [ 0.23021264  0.96830241]]


In [47]:
#find projections
max_lamb_idx = np.argmax(lambd)
print(lambd[max_lamb_idx])
w = vecs[:,max_lamb_idx]
print(w)

0.9699647487186839
[0.97314035 0.23021264]


In [48]:
#reduce dimensionality
x1 = np.dot(x1,w.reshape(n_features,1))
x2 = np.dot(x2,w.reshape(n_features,1))
x3 = np.dot(x3,w.reshape(n_features,1))

In [49]:
print(x1)

[[ 0.4832673 ]
 [-0.19569625]
 [ 1.82709223]
 [ 0.5517732 ]
 [ 3.56124444]]
