In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
#generate sample points
n = 5
x1 = np.random.multivariate_normal([2,3],[[2,0.8],[0.8,3]],n)
x2 = np.random.multivariate_normal([5,4],[[1.5,0.6],[0.6,2]],n)
x3 = np.random.multivariate_normal([1,3],[[3.7,0.3],[0.3,2.5]],n)

In [5]:
print(x1.shape)
print(x2.shape)
print(x3.shape)

(5, 2)
(5, 2)
(5, 2)


In [6]:
#X = np.vstack((x1,x2,x3))
X = np.vstack((x1,x2,x3))
print('original data:\n',X)
n_samples,n_features = X.shape
d_features = 1 #reduced dimensionality
print('no. of samples:',n_samples)
print('no. of features:',n_features)

original data:
 [[ 2.31206285  3.84668649]
 [ 2.62057273  4.25276128]
 [ 1.25929619  2.59238549]
 [ 2.41620021  4.31773078]
 [ 2.13989564  6.10709047]
 [ 3.89750209  1.8147391 ]
 [ 3.71082389  0.68239536]
 [ 6.63590593  2.25186463]
 [ 2.94548054  4.21030746]
 [ 5.62583027  7.49904786]
 [ 4.53820123  0.14323434]
 [ 0.20103765  3.13886547]
 [-2.54099432  2.09289014]
 [-1.73564793  0.85428146]
 [ 5.41154171  3.9126181 ]]
no. of samples: 15
no. of features: 2


In [7]:
#calculate mean of the data
mu = np.mean(X,axis=0).reshape(1,n_features)
print('mean:',mu)
#print(mu.shape)

mean: [[2.62918058 3.18112656]]


In [8]:
#subtract mean from data to make mean of data 0
X = X - mu
print('zero mean data:\n',X)

zero mean data:
 [[-0.31711773  0.66555993]
 [-0.00860785  1.07163472]
 [-1.36988439 -0.58874107]
 [-0.21298036  1.13660422]
 [-0.48928494  2.92596391]
 [ 1.26832151 -1.36638746]
 [ 1.08164332 -2.49873121]
 [ 4.00672535 -0.92926193]
 [ 0.31629996  1.0291809 ]
 [ 2.99664969  4.3179213 ]
 [ 1.90902065 -3.03789222]
 [-2.42814293 -0.04226109]
 [-5.1701749  -1.08823642]
 [-4.36482851 -2.3268451 ]
 [ 2.78236113  0.73149154]]


In [10]:
#compute covariance matrix
cov = np.dot(X.T,X)/15
print('covariance matrix:\n',cov)

covariance matrix:
 [[6.2159056  1.0759624 ]
 [1.0759624  3.78887336]]


In [11]:
#find eigen values and eigen vectors
#lambd contains eigen values in ascending order
#each column of vecs contains eigen vectors. vecs[:,i] is the eigen vector corresponding to lambd[i]
lambd,vecs = np.linalg.eigh(cov)
print('eigen values:',lambd)
print('eigen vectors:\n',vecs)

eigen values: [3.38056444 6.62421452]
eigen vectors:
 [[ 0.35479496 -0.93494414]
 [-0.93494414 -0.35479496]]


In [12]:
#project the data
#select eigen vectors corresponding to the maximum eigen values
w = vecs[:,1].reshape(n_features,d_features)
print(w)

[[-0.93494414]
 [-0.35479496]]


In [14]:
final_data = np.dot(w.T,X.T).reshape(n_samples,d_features)
print('Reduced data(1D):\n',final_data)

Reduced data(1D):
 [[ 0.06035006]
 [-0.37216274]
 [ 1.48964774]
 [-0.2041367 ]
 [-0.58066315]
 [-0.70102238]
 [-0.12473885]
 [-3.41636693]
 [-0.66087098]
 [-4.33367675]
 [-0.70699883]
 [ 2.28517202]
 [ 5.2199255 ]
 [ 4.90642372]
 [-2.86088174]]
