In [1]:
#import numpy as np
import matplotlib.pyplot as plt

In [2]:
%matplotlib inline

In [43]:
#generate sample points
n = 50
x1 = np.random.multivariate_normal([2,3],[[2,0.8],[0.8,3]],n)
x2 = np.random.multivariate_normal([5,4],[[1.5,0.6],[0.6,2]],n)
x3 = np.random.multivariate_normal([1,3],[[3.7,0.3],[0.3,2.5]],n)

In [44]:
print(x1.shape)
print(x2.shape)
print(x3.shape)

(50, 2)
(50, 2)
(50, 2)


In [45]:
X = np.vstack((x1,x2,x3))
print(X.shape)
n_samples,n_features = X.shape
d_features = 1 #reduced dimensionality
print('no. of samples:',n_samples)
print('no. of features:',n_features)

(150, 2)
no. of samples: 150
no. of features: 2


In [46]:
#calculate mean of the data
mu = np.mean(X,axis=0).reshape(1,n_features)
print(mu.shape)

(1, 2)


In [47]:
#subtract mean from data to make mean of data 0
X = X - mu
print(X.shape)

(150, 2)


In [48]:
#compute covariance matrix
cov = np.dot(X.T,X)
print(cov)

[[816.04884176 274.14883664]
 [274.14883664 436.09920498]]


In [49]:
#find eigen values and eigen vectors
#lambd contains eigen values in ascending order
#each column of vecs contains eigen vectors. vecs[:,i] is the eigen vector corresponding to lambd[i]
lambd,vecs = np.linalg.eigh(cov)
print(lambd)
print(vecs)

[292.53539554 959.6126512 ]
[[ 0.46391073 -0.88588195]
 [-0.88588195 -0.46391073]]


In [50]:
#project the data
#select eigen vectors corresponding to the maximum eigen values
w = vecs[:,-1].reshape(n_features,d_features)
print(w)

[[-0.88588195]
 [-0.46391073]]


In [51]:
final_data = np.dot(w.T,X.T).reshape(n_samples,d_features)
print(final_data)

[[ 1.29386801]
 [-0.41091859]
 [-0.1214389 ]
 [ 3.37942845]
 [-0.61604518]
 [ 2.42926472]
 [-1.82773461]
 [ 1.9082842 ]
 [ 0.18255328]
 [ 0.59270474]
 [-0.36505841]
 [-0.28772787]
 [-0.66005655]
 [ 0.83980248]
 [ 0.62381132]
 [ 1.59452449]
 [ 0.74346148]
 [ 2.51882112]
 [ 3.21538214]
 [ 0.76645415]
 [-0.37824235]
 [-0.13191288]
 [ 1.13358531]
 [ 2.44811472]
 [-0.03982217]
 [-2.34202363]
 [ 1.4534004 ]
 [-1.14811545]
 [ 0.13030535]
 [-1.61841197]
 [-0.64264264]
 [ 0.53785738]
 [ 0.56819784]
 [ 0.38857167]
 [ 0.766377  ]
 [ 3.96512169]
 [ 3.62698432]
 [ 2.75194866]
 [ 3.58940687]
 [-0.60291443]
 [ 0.77676731]
 [ 2.22784117]
 [-0.59367449]
 [ 2.76876431]
 [ 2.18126368]
 [ 0.76525409]
 [ 3.54141868]
 [ 1.79043638]
 [ 2.50411937]
 [-2.42373988]
 [ 0.43541978]
 [-4.28796893]
 [-0.76710631]
 [-4.67657855]
 [-2.09214047]
 [-1.67096028]
 [-2.08000476]
 [-4.71278587]
 [-0.71870608]
 [-2.85813514]
 [-2.36363242]
 [-4.27510352]
 [-2.74756032]
 [-2.24027315]
 [-2.17889223]
 [-1.34788258]
 [-2.24584